apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment challenge 2
  labels:
    name: deployment_challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        os: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          command: ["/bin/bash", "-c"]
          args:
            - sleep 300  
    